### ISSUE TITLE
DESCRIBE and SHOW TABLES return empty results

### ISSUE THREAD

**Issue by radcheb** [laughingman7743/PyAthena#114]
Since 1.9.0 or 1.10.0 (was working in 1.8.0)  all `SHOW TABLES` and  `DESCRIBE` return empty results.

Here is a code example with 1.8.0, results are obfuscated for confidentiality concerns.

```python
cursor = connect(cursor_class=PandasCursor,
                aws_access_key_id='YOUR_ACCESS_KEY_ID',
                 aws_secret_access_key='YOUR_SECRET_ACCESS_KEY',
                 s3_staging_dir='s3://YOUR_S3_BUCKET/path/to/',
                 region_name='us-west-2').cursor()
cursor.execute("SHOW TABLES").as_pandas()
```
![image](https://user-images.githubusercontent.com/5963615/73284978-9de45000-41f5-11ea-9958-f384d16286ce.png)

And here are the same result but with 1.10.0

![image](https://user-images.githubusercontent.com/5963615/73285134-de43ce00-41f5-11ea-9784-85888eca3769.png)

The same problem exists when using a `DESCRIBE` query.

**Comment by laughingman7743** [comment]
Thanks. I'll investigate on this weekend.

**Comment by laughingman7743** [comment]
https://github.com/laughingman7743/PyAthena/commit/b60154f751275464c05dca4e029a6fd8955101d5#diff-a42fef67d79fa725953a9bc7f7e313f1R360-R363
The changes around here seem to be relevant.
In the case of PandasCursor, any version will likely result in an error.

`SHOW TABLES` query has Athena statement type Utility. In this case, the file output to S3 will be a TEXT file instead of CSV. I need an implementation that handles this difference.

**Comment by laughingman7743** [comment]
I fixed it in the following branch. Please check. 🙏
https://github.com/laughingman7743/PyAthena/pull/116

**Comment by axelborja** [comment]
@laughingman7743 thanks for your reactivity. 👏
