### ISSUE TITLE
PandasCursor: Add support for UNLOAD and resulting file types

### ISSUE THREAD

**Issue by annisall** [laughingman7743/PyAthena#242]
Now that [Athena supports UNLOAD in the queries](https://docs.aws.amazon.com/athena/latest/ug/unload.html), it means a user can have their result in Apache Parquet, ORC, Apache Avro, or JSON file. PandasCursor currently supports only csv files.

**Comment by ztane** [comment]
Using parquet instead of CSV could greatly increase the speed.

**Comment by laughingman7743** [comment]
In PandasCursor, is it better to wrap the SELECT statement with UNLOAD command, output it to S3 as Parquet, and read that file directly for better performance? Do you have any comparison results?

**Comment by DyfanJones** [comment]
Hi all, 

`awswrangler` does something similar, however they use `ctas` queries to read in `parquet` format. Here is their example and benchmarks: https://aws-data-wrangler.readthedocs.io/en/stable/tutorials/006%20-%20Amazon%20Athena.html

In short they got a 13x to 24x performance improvement.

I am currently investigating an approach using AWS Athena unloads (for my R to Athena packages). There seems to be a similar amount of improvement https://github.com/DyfanJones/noctua/issues/160 when pulling the entire data back.

Hope this helps with performance comparison @laughingman7743

**Comment by laughingman7743** [comment]
@DyfanJones Thank you for your information.
It looks like good performance. I'm going to try to implement it using the UNLOAD command.

**Comment by DyfanJones** [comment]
Did some basic benchmarking to check comparison on sagemaker `ml.t3.xlarge` instance:

Running: "SELECT * FROM noaa" query from https://aws-data-wrangler.readthedocs.io/en/stable/tutorials/006%20-%20Amazon%20Athena.html example.

```
noctua: 2.2.0.9000
R: 4.1.1

Results:
csv:
seconds:160.567

unload:
seconds: 39.232
4X faster

cache unload:
seconds:11.924
13.4X faster
```

```
awswrangler version: 2.11.0
python: 3.6.13

Results:
csv:
seconds: 189

ctas:
seonds: 92
2.05X faster

ctas with categories:
seconds: 35.9
5.26X faster
```
For more details please check out: R: https://github.com/DyfanJones/noctua/issues/160#issuecomment-934370622 & Python: https://github.com/DyfanJones/noctua/issues/160#issuecomment-934410290
It looks like `unload` runs comparible to `ctas` method. Plus with the bonus of not requiring any glue permissions. Happy to go over the approach I have used to implement `unload` (if needed 😄)

**Comment by ztane** [comment]
One needs to note that unlike `CSV`, `UNLOAD` doesn't fully preserve `ORDER BY` as it can and will produce multiple files each containing a subset of rows and one might need to do a merge run over the files to get them in order.

**Comment by laughingman7743** [comment]
Sorry for the very late reply.

I am trying to implement the UNLOAD option of PandasCursor in the following branch.
https://github.com/laughingman7743/PyAthena/pull/307

The UNLOAD command splits the file if the result is large, allowing the split files to be read in parallel, which makes retrieving results ultra fast.
However, while the sort order is preserved within a single file, the sort order is not preserved across multiple files. I believe this is a limitation of the UNLOAD command.

https://docs.aws.amazon.com/athena/latest/ug/unload.html#unload-considerations-and-limitations
> No global ordering of files – UNLOAD results are written to multiple files in parallel. If the SELECT query in the UNLOAD statement specifies a sort order, each file's contents are in sorted order, but the files are not sorted relative to each other.

Since the sort order depends on the order by statement of the query being executed, re-sorting a DataFrame requires parsing the query to see if order by is specified and, if so, which fields are specified.
This is a very difficult implementation, and it would be better to specify this limitation when using the UNLOAD option and leave it up to the user to decide whether or not to use it.
