### ISSUE TITLE
Ctrl-C while running query kills python session

### ISSUE THREAD

**Issue by memeplex** [laughingman7743/PyAthena#27]
Signal handling should be improved if possible, because both:

1. Being unable to abort at all, and
2. Abort at the cost of quitting a running REPL

are barely acceptable for interactive usage.

**Comment by memeplex** [comment]
Sorry, this was for the jdbc version, I've just realized there were two related projects, I'm going to give this one a try.

**Comment by memeplex** [comment]
@laughingman7743 could you clarify the relationship between both projects? Which do you consider to be more mature/stable? Why do you maintain both versions?

**Comment by laughingman7743** [comment]
I hope that PyAthena will be used. I think that is more stable than the JDBC version.
The JDBC version was created because Athena only supports JDBC connections.
Currently Athena supports RestAPI, so it is best to use it from Python.

But, since the JDBC version is used more than the RestAPI version, it is only maintaining it.

|    | download_count |
| - | ---------------- |
| PyAthena | 11,148 |
| PyAthenaJDBC | 88,346 |

It is the number of downloads in the most recent month. (use https://github.com/ofek/pypinfo)
