### ISSUE TITLE
SQLalchemy cast to String not working anymore?

### ISSUE THREAD

**Issue by luca-ferreri** [laughingman7743/PyAthena#289]
first of all: I really appreciate this project, it helps me a lot everyday. Thank you @laughingman7743 and other contributors!

I have a question/issue report: with the last realease (v2.5.0) some features changed (probabily this #286) and something that was working very well with version 2.4.0 is not working anymore.

Let's say that I have an integer column '_integer_col_' in the table '_some_table_' in the database '_some_db_'.

with v2.4.0 the SQLalchemy query
```python
select(
    some_table.integer_col.cast(String)
)
```
produces the following SQL
```SQL
SELECT CAST("some_db"."some_table"."integer_col" AS VARCHAR)
FROM "some_db"."some_table"
```
which is perfect.

while with v2.5.0 the same query produces the following SQL
```SQL
SELECT CAST("some_db"."some_table"."integer_col" AS STRING)
FROM "some_db"."some_table"
```

which return the following error in Athena

`SYNTAX_ERROR: line xxx:yyy: Unknown type: string`

As workround I could change the query as follows
```python
select(
    some_table.integer_col.cast(VARCHAR(n))
)
```

which, however, is not very convenient to use since sometimes is not possible to know the length of the string n.

What I am missing?

**Comment by laughingman7743** [comment]
As you point out, #286 changes the handling of VARCHAR and STRINGS. When I was discussing the change in #279, I made the change to the STRING type if no length is specified, as it is an error if the length is not specified in the VARCHAR when the table is created. However I overlooked that Athena cannot CAST to STRING.
https://docs.aws.amazon.com/athena/latest/ug/data-types.html
I would like to consider some way to work around this issue.

**Comment by andreaschiappacasse** [comment]
A workaround to revert to old behaviour at runtime is to specify:

  ```python
@compiles(String)
  def compile_varchar(element, compiler, **kw):
      if element.length == 'unbounded':
          return "VARCHAR"
      else:
          return compiler.visit_VARCHAR(element, **kw)

```

and then use it as in:

```python
select(
    some_table.integer_col.cast(String('unbounded'))
)
```

when a cast to VARCHAR is needed.

@laughingman7743 I think that a possible "correct" solution would be specifying two different _TypeCompiler_,s one (with hive mapping) to be used by the _DDLCompiler_ and one (with presto mapping) to be used by the _SQLCompiler_. 

It could then be possible to override the attribute _type_compiler_ of the _DDLCompiler_ (which by default maps to the _Dialect_ one) in order to make it use the one with the correct mapping.
