### ISSUE TITLE
Add pd.Timestamp to formatters

### ISSUE THREAD

**Issue by reesehopkins** [laughingman7743/PyAthena#366]
Love the library! I may be doing this incorrectly, but in the `_DEFAULT_FORMATTERS`, I do not see `pd.Timestamp` (pandas) as a formatter. So if I run something like this...

```python
import pyathena
import pandas as pd
import sqlalchemy as sa

conn = pyathena.connect('...')
meta = sa.Meta(schema='schema')
table = sa.Table('table_name', meta, autoload_with=conn)
stmt = sa.select(table.c.other_col).where(table.c.date_time_col > pd.Timestamp('2022-08-15'))
df = pd.read_sql_query(stmt, conn)
```
I'll get a `TypeError: <class 'pandas._libs.tslibs.timestamps.Timestamp'> is not defined formatter.`

Anyway, I think it should have the same format as `datetime.datetime`? .

**Comment by laughingman7743** [comment]
The default formatter can be easily changed, so it is a good idea to customize the type and format function pairs you need.
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/formatter.py#L157-L169
https://github.com/laughingman7743/PyAthena/blob/master/pyathena/connection.py#L62
Of course, you can include Pandas Timestamp in the default formatter, but since Pandas is an Extra package, it is not necessary for users who do not use Pandas. Including it in the default formatter would make it difficult to prevent Pandas package imports for users who do not use Pandas packages. I do not want to include it in the default formatter.

**Comment by reesehopkins** [comment]
Oh nice! Thanks for the code links. Didn't realize pandas was an extra dependency. Agree it's best to keep it off the default formatters. Closing.
